apiVersion: v1
kind: Service
metadata:
  name : usermgmt-webapp-nodeport-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  selector:
    app : usermgmt-webapp
  ports:
    - name: http
      port: 80 # Service Port
      targetPort: 8080 # Container Port
  type: LoadBalancer