variable "common_tags" {}
variable "naming_prefix" {}
variable "eks_basic_user" {}
variable "eks_admin_user" {}
variable "eks_worker_node_role_name" {}
variable "cluster_id" {}
variable "cluster_endpoint" {}
variable "cluster_certificate_authority_data" {}
variable "eks_admin_group_name" {}
variable "eks_admin_role_name" {}
variable "eks_readonly_role_name" {}
variable "eks_read_only_group_name" {}
variable "eksreadonly_user_name" {}